---
- hosts: nodes
  vars:
    max_pv: 2
  tasks:
    - name: Install NFS to all nodes
      yum:
        name: '{{ packages }}'
      vars: 
        packages: 
          - nfs-utils

    - name: Enable SELinux for nfs
      command: setsebool -P virt_use_nfs 1

    - name: Enable  NFS server to node1
      command: systemctl enable nfs-server.service
      when: inventory_hostname == 'node1.10.1.3.3.nip.io'
      
    - name: Start NFS server to node1
      command: systemctl start nfs-server.service
      when: inventory_hostname == 'node1.10.1.3.3.nip.io'

    - name: Create Persistent Volume directory
      command: "mkdir -p /var/lib/origin/nfs/pv{{ item }}"
      with_sequence: "0-{{ max_pv }}"
      when: inventory_hostname == 'node1.10.1.3.3.nip.io'
     
    - name: Set Owner of Persistent Volume Directory
      command: chown -R nfsnobody.nfsnobody /var/lib/origin/nfs
      when: inventory_hostname == 'node1.10.1.3.3.nip.io'

    - name: Set Permissions of Persistent Volume directory
      command: chmod -R 770 /var/lib/origin/nfs
      when: inventory_hostname == 'node1.10.1.3.3.nip.io'
    
    - name: Add to /etc/exports file
      lineinfile:
        path: /etc/exports
        regexp: "/var/lib/origin/nfs/pv{{ item }} *(rw,root_squash)"    
        line: "/var/lib/origin/nfs/pv{{ item }} *(rw,root_squash)"
      with_sequence: "0-{{ max_pv }}"
      when: inventory_hostname == 'node1.10.1.3.3.nip.io'

    - name: Export the filesystems
      command: exportfs -a
      when: inventory_hostname == 'node1.10.1.3.3.nip.io'

    - name: Fix the image for origin-recycler
      lineinfile: 
        path: /etc/sysconfig/origin-master-controllers
        regexp: "OPENSHIFT_RECYCLER_IMAGE=\"openshift/origin-recycler:v3.9.0\""
        line: "OPENSHIFT_RECYCLER_IMAGE=\"openshift/origin-recycler:v3.9.0\""
      when: inventory_hostname == 'master.10.1.3.2.nip.io'

    - name: Restart OpenShift controllers
      command: systemctl restart origin-master-controllers
      when: inventory_hostname == 'master.10.1.3.2.nip.io'

    - name: Create PV objects in OpenShift
      shell:
        cmd: |
          cat << EOF | oc create -f -
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: pv{{ item }}
          spec:
            capacity:
              storage: 5Gi
            accessModes:
            - ReadWriteOnce
            nfs:
              path: /var/lib/origin/nfs/pv{{ item }}
              server: 10.1.3.3
            persistentVolumeReclaimPolicy: Recycle
          EOF
      with_sequence: "0-{{ max_pv }}"
      when: inventory_hostname == 'master.10.1.3.2.nip.io'

